# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "OpenTalk Controller service"
documentation = "https://docs.rs/opentalk-controller-service"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-controller-service"
publish = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
kustos.workspace = true
lapin-pool.workspace = true
log = { workspace = true, features = ["serde"] }
md5.workspace = true
opentalk-controller-service-facade.workspace = true
opentalk-controller-settings.workspace = true
opentalk-controller-utils.workspace = true
opentalk-database.workspace = true
opentalk-db-storage.workspace = true
opentalk-keycloak-admin.workspace = true
opentalk-mail-worker-protocol.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types-api-v1 = { workspace = true, features = ["diesel"] }
opentalk-types-common = { workspace = true, features = ["kustos"] }
opentelemetry = { workspace = true, features = ["metrics", "trace"] }
serde_json.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["signal"] }
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
