# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-polls"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
futures.workspace = true
log.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types = { workspace = true, features = ["backend"] }
redis-args.workspace = true
redis.workspace = true
serde.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
opentalk-test-util = { workspace = true, features = ["controller"] }
pretty_assertions.workspace = true
serial_test.workspace = true
actix-rt.workspace = true
