# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-polls"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
controller = { path = "../controller", package = "opentalk-controller-core" }
redis = "0.22"
redis-args = { path = "../redis-args", package = "opentalk-redis-args" }
serde = { version = "1", features = ["derive"] }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }

[dev-dependencies]
test-util = { path = "../test-util", package = "opentalk-test-util", features = ["controller"] }
pretty_assertions = "1.3"
serial_test = "1"
actix-rt = "2.8"
