# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "OpenTalk API v1 data types"
documentation = "https://docs.rs/opentalk-types-api-v1"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-types-api-v1"
publish = true
repository.workspace = true
version.workspace = true

[features]
backend = []
frontend = []
