# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Common types and traits for OpenTalk crates"
documentation = "https://docs.rs/opentalk-types-common"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-types-common"
publish = true
repository.workspace = true
version.workspace = true

[features]
backend = ["diesel", "rand", "serde", "utoipa"]
diesel = ["dep:diesel", "dep:opentalk-diesel-newtype", "serde"]
frontend = ["dep:opentalk-client-shared", "http"]
rand = ["uuid/v4"]
serde = ["dep:serde", "uuid/serde"]
utoipa = ["dep:serde_json", "dep:utoipa", "serde"]

[dependencies]
derive_more = { workspace = true, features = [
  "as_ref",
  "display",
  "from",
  "from_str",
  "into",
] }
diesel = { workspace = true, features = ["uuid"], optional = true }
http = { workspace = true, optional = true }
opentalk-client-shared = { workspace = true, optional = true }
opentalk-diesel-newtype = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
utoipa = { workspace = true, features = ["uuid"], optional = true }
uuid.workspace = true

[package.metadata.cargo-machete]
ignored = [
  # Required by `utoipa::ToSchema`, not detected by compiler
  "serde_json",
]
