# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-shared-folder"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
controller = { path = "../controller", package = "opentalk-controller-core" }
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
database = { path = "../database", package = "opentalk-database" }
log.workspace = true
redis = "0.22"
redis-args = { path = "../redis-args", package = "opentalk-redis-args" }
signaling-core = { path = "../signaling-core", package = "opentalk-signaling-core" }
tracing.workspace = true
types = { path = "../types", package = "opentalk-types", features = ["backend"] }

[dev-dependencies]
pretty_assertions = "1.3"
serial_test = "1"
test-util = { path = "../test-util", package = "opentalk-test-util", features = ["controller"]}
actix-rt.workspace = true
