# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-shared-folder"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
log.workspace = true
opentalk-database.workspace = true
opentalk-db-storage.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types = { workspace = true, features = ["backend"] }
redis-args.workspace = true
redis.workspace = true
snafu.workspace = true
tracing.workspace = true

[dev-dependencies]
actix-rt.workspace = true
opentalk-test-util = { workspace = true, features = ["controller"] }
pretty_assertions.workspace = true
serial_test.workspace = true
