# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

doc-valid-idents = ["..", "OpenTalk"]
ignore-interior-mutability = [
  "bytes::Bytes",
  "opentalk_janus_media::mcu::McuClient",
]
