# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

---
image: git.opentalk.dev:5050/opentalk/backend/containers/rust:1.83.0-bookworm

stages:
  - lint
  - test
  - build
  - check
  - package
  - trigger

variables:
  OPENTALK_CONTROLLER_PROJECT: opentalk-controller
  # Enable one network per build for the test container and services
  FF_NETWORK_PER_BUILD: 'true'
  # Will be set to the same namespace as the source project for a MR,
  # or the same namespace as the current project for the `main` branch.
  # Can be overridden entirely from project settings.
  ENTERPRISE_CANARY_PROJECT: ''
  ENTERPRISE_PROJECT: $CI_PROJECT_NAMESPACE/controller-enterprise
  ENTERPRISE_REF: main
  COMMUNITY_EDITION_UPSTREAM: $CI_PROJECT_PATH
  KANIKO_IMAGE: gcr.io/kaniko-project/executor:debug

.default_job_condition: &default_job_condition
  needs: []
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'

.test:types:
  stage: test
  # Ensures that the crate can be built with each relevant feature individually
  variables:
    RUSTFLAGS: -D warnings
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        paths:
          - crates/opentalk-types-common/**/*
          - crates/opentalk-types-signaling/**/*
          - crates/$PACKAGE/**/*
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  parallel:
    matrix:
      - FEATURES: ['']
        EXTRA_ARGS: ['', --no-default-features]
  script:
    - cargo clippy --package $PACKAGE $EXTRA_ARGS --features=$FEATURES
    - cargo test --package $PACKAGE $EXTRA_ARGS --features=$FEATURES

include: crates/**/gitlab-ci.yml

trigger_enterprise_ci:
  stage: trigger
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^main$/ || $CI_PIPELINE_SOURCE == 'merge_request_event'
      exists:
        - crates/community-modules/Cargo.toml
  script:
    - set -x
    - shopt -s expand_aliases
    - |
      if [ "$ENTERPRISE_CANARY_PROJECT" == "" ]; then
        if [[ $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH != "" ]]; then
          SOURCE_PROJECT_NAMESPACE="${CI_MERGE_REQUEST_SOURCE_PROJECT_PATH%\/*}"
          export ENTERPRISE_CANARY_PROJECT="$SOURCE_PROJECT_NAMESPACE"/controller-enterprise-canary
          export ENTERPRISE_PROJECT="$SOURCE_PROJECT_NAMESPACE"/controller-enterprise
          export COMMUNITY_EDITION_UPSTREAM="$CI_MERGE_REQUEST_SOURCE_PROJECT_PATH"
        else
          export ENTERPRISE_CANARY_PROJECT="$CI_PROJECT_NAMESPACE"/controller-enterprise-canary
          export ENTERPRISE_PROJECT="$CI_PROJECT_NAMESPACE"/controller-enterprise
          export COMMUNITY_EDITION_UPSTREAM="$CI_PROJECT_PATH"
        fi
      fi
    # https://stackoverflow.com/a/28055173
    - alias encode_uri='perl -pe '\''s/([^a-zA-Z0-9_.!~*()'\''\'\'''\''-])/sprintf("%%%02X",ord($1))/ge'\'
    - export ENCODED_ENTERPRISE_PROJECT="$(echo -n "$ENTERPRISE_PROJECT" | encode_uri)"
    - |
      curl \
        --request POST \
        --form "token=$CI_JOB_TOKEN" \
        --form "ref=$ENTERPRISE_REF" \
        --form "variables[CANARY_REPO_PROJECT_PATH]=$ENTERPRISE_CANARY_PROJECT" \
        --form "variables[COMMUNITY_EDITION_COMMITISH]=$CI_COMMIT_SHA" \
        --form "variables[COMMUNITY_EDITION_UPSTREAM]=$COMMUNITY_EDITION_UPSTREAM" \
        "$CI_API_V4_URL/projects/$ENCODED_ENTERPRISE_PROJECT/trigger/pipeline"

trigger_changelog_preview:
  stage: trigger
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    PIPELINE_PROJECT_PATH: $CI_PROJECT_PATH
    PIPELINE_MERGE_REQUEST_PROJECT_PATH: $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
    PIPELINE_MERGE_REQUEST_SOURCE_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    PIPELINE_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
  trigger: opentalk/tools/check-changelog

lint:fmt:
  stage: lint
  <<: *default_job_condition
  script:
    - cargo +nightly fmt -- --check

lint:clippy:
  stage: lint
  <<: *default_job_condition
  script:
    - cargo clippy --workspace --all-features --tests -- --deny warnings

lint:doc:
  stage: lint
  <<: *default_job_condition
  variables:
    RUSTDOCFLAGS: -Dwarnings
  script: cargo doc --workspace --no-deps

lint:shellcheck:
  image: koalaman/shellcheck-alpine:latest
  stage: lint
  <<: *default_job_condition
  before_script:
    - apk update
    - apk add git
  script: git ls-files "*.sh" -z | xargs -0r shellcheck

lint:dependency_check:
  stage: lint
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - Cargo.lock
        - deny.toml
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script: cargo-deny --workspace check --deny unmatched-skip --deny license-not-encountered

lint:unnecessary_dependencies:
  stage: lint
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script: if ! cargo machete --version; then cargo install cargo-machete; fi
  script: cargo machete --with-metadata

lint:yaml:
  stage: lint
  <<: *default_job_condition
  image: alpine:3.21
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

lint:toml:
  stage: lint
  <<: *default_job_condition
  script: taplo fmt --check

lint:openapi:
  stage: lint
  <<: *default_job_condition
  image:
    name: redocly/cli:1.26.1
    entrypoint: ['']
  script:
    - /usr/local/bin/openapi lint api/controller/frontend_api.yaml

lint:openapi-spectral:
  stage: lint
  <<: *default_job_condition
  image:
    name: stoplight/spectral
    entrypoint: ['']
  script:
    - spectral lint --ruleset ci/spectral/openapi.yml lint api/controller/frontend_api.yaml

lint:markdown:
  stage: lint
  <<: *default_job_condition
  image: registry.gitlab.com/pipeline-components/markdownlint:latest
  script:
    - mdl --style .markdown_style.rb  --warnings .

lint:licensing:
  stage: lint
  <<: *default_job_condition
  image:
    name: fsfe/reuse:latest
    entrypoint: ['']
  script:
    - reuse lint

lint:commit:
  cache: {}
  image: node:lts-alpine
  stage: lint
  needs: []
  rules:
    # Run in merge requests only.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git
    - npm install -g @commitlint/cli @commitlint/config-conventional
  script:
    - npx commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to HEAD --verbose

lint:commit-signature:
  stage: lint
  needs: []
  rules:
    # Run in merge requests only.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    # %G? will log signature information for a commit. `N` stands for "no signature", `B` for "bad signature"
    # refer to https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-emGem
    # grep checks that the output does not contain any "N" or "B" characters.
    - >
      git log --format=format:'%G?' $CI_MERGE_REQUEST_DIFF_BASE_SHA..HEAD
      | grep --null-data --quiet --invert-match --regexp="N" --regexp="B"

lint:mod-rs-files:
  # This job is needed until we can fully deny the `self_named_module_files` in clippy.
  # The blocker for this is a bug in clippy that triggers false positives in some cases.
  # https://github.com/rust-lang/rust-clippy/issues/11916
  stage: lint
  <<: *default_job_condition
  variables:
    # For getting color output from `tput`
    TERM: xterm-256color
  before_script: apt-get update && apt-get install -y fd-find
  script: ./ci/lint-mod-rs-files.sh

lint:justfile:
  stage: lint
  <<: *default_job_condition
  before_script: if ! just --version; then cargo install just; fi
  script:
    # The `--fmt` command-line parameter is still unstable, but valuable anyway.
    - just --unstable --fmt --check

test:cargo_test:
  stage: test
  <<: *default_job_condition
  artifacts:
    paths:
      - target/coverage/html
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/coverage/cobertura.xml
  coverage: '/Coverage: \d+(?:\.\d+)?/'
  variables:
    # Set ENV vars for services
    POSTGRES_DB: opentalk
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password123
    POSTGRES_HOST_AUTH_METHOD: trust
    # Used for integration tests
    POSTGRES_BASE_URL: postgres://postgres:password123@postgres:5432
    DATABASE_NAME: opentalk
    KUSTOS_TESTS_DATABASE_URL: postgres://postgres:password123@postgres:5432/kustos
    REDIS_ADDR: redis://redis:6379/
    # Used for coverage
    COVERAGE_XML_PATH: 'concat("Coverage: ", 100 * string(//coverage/@line-rate), "%")'
  services:
    - name: postgres:17-alpine
      alias: postgres
    - name: redis:7-alpine
      alias: redis
  before_script:
    - rustup component add rustfmt llvm-tools-preview
    # libxml2-utils contains the xmllint command used below
    - apt-get update && apt-get install -y libxml2-utils
    - cargo install diesel_cli --version ~2 --no-default-features --features="postgres"
  script:
    - RUSTFLAGS="-C instrument-coverage -C link-arg=-fuse-ld=lld"
      LLVM_PROFILE_FILE="$(pwd)/target/coverage/raw/coverage-%p-%m.profraw"
      cargo test --workspace --locked

    # Extract code coverage data
    - grcov target/coverage/raw
      --binary-path ./target/debug/
      --source-dir .
      --output-types cobertura,html
      --branch
      --ignore-not-existing
      --ignore "*cargo*"
      --output-path target/coverage

    # Print out the coverage percentage for GitLab
    - xmllint --xpath "$COVERAGE_XML_PATH" target/coverage/cobertura.xml

test:cargo_xtask:
  stage: test
  <<: *default_job_condition
  variables:
    POSTGRES_DB: opentalk
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password123
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_BASE_URL: postgres://postgres:password123@postgres:5432
    DATABASE_NAME: opentalk
  services:
    - name: postgres:17-alpine
      alias: postgres
  script:
    - cargo install diesel_cli --version ~2 --no-default-features --features="postgres"
    # Verify that the HEAD schema.rs matches the actual HEAD migration database schema.
    - RUST_LOG=error cargo xtask verify-db-schema --postgres-url="${POSTGRES_BASE_URL}"

test:container:
  stage: test
  <<: *default_job_condition
  image:
    name: $KANIKO_IMAGE
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/container/Dockerfile
      --no-push
      --force

build:
  stage: build
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG != null
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    VERGEN_GIT_SHA: $CI_COMMIT_SHA
    VERGEN_GIT_BRANCH: $CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - target/release/opentalk-controller
    expire_in: 1 week
  before_script:
    - apt-get update && apt-get install -y libpq-dev musl-tools protobuf-compiler
  script:
    - cargo auditable build --release --locked --workspace

check:opentalk-types:
  stage: check
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  # Ensures that the `types` crate can be built with each relevant feature individually
  variables:
    RUSTFLAGS: -D warnings
  parallel:
    matrix:
      - FEATURES:
          [
          '',
            frontend,
            backend,
            actix,
            axum,
            diesel,
            kustos,
            redis,
            serde,
            utoipa,
          ]
        EXTRA_ARGS: ['', --no-default-features]
  script:
    - cargo check --package opentalk-types $EXTRA_ARGS --features=$FEATURES

check:er-diagram:
  stage: check
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - target/docs/temporary/database/er-diagram.mermaid
  variables:
    # Set ENV vars for services
    POSTGRES_DB: opentalk
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password123
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_BASE_URL: postgres://postgres:password123@postgres:5432
    OPENTALK_CTRL_DATABASE__URL: postgres://postgres:password123@postgres:5432/opentalk
  services:
    - name: postgres:17-alpine
      alias: postgres
  script:
    - ci/docs-generate-mermaid.sh

check:mail-worker-protocol-schema-and-examples:
  stage: check
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - target/docs/temporary/mail-worker-protocol
  script:
    - ci/docs-generate-mail-worker-protocol-schema-and-examples.sh

check:docs-generated-parts:
  stage: check
  image:
    name: git.opentalk.dev:5050/opentalk/tools/opentalk-ci-doc-updater:v0.1.0
    entrypoint: ['']
  needs:
    - job: build
      artifacts: true
    - job: check:er-diagram
      artifacts: true
    - job: check:mail-worker-protocol-schema-and-examples
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    # Set ENV vars for services
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_PORT: '5672'
    OPENTALK_CTRL_RABBIT_MQ__URL: amqp://guest:guest@rabbitmq:5672
  services:
    - name: rabbitmq:4.0
      alias: rabbitmq
  before_script:
    - apt-get update && apt-get install -y git
    # lowkey replacement for a rabbitmq health check
    - sleep 10
  script:
    - ci/docs-update-generated-parts.sh
    - |
      if ! git diff --exit-code; then
        echo "Generated parts of documentation changed, run ci/docs-update-generated-parts.sh and commit the result"
        exit 1
      fi

check:openapi:
  stage: check
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - ./ci/update-openapi-spec.sh
    - |
      if ! git diff --ignore-space-at-eol --exit-code --submodule=diff; then
        echo "Generated parts of documentation changed, run ci/update-openapi-spec.sh and commit the result"
        exit 1
      fi

package:container-controller-mr:
  stage: package
  needs:
    - build
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  image:
    name: $KANIKO_IMAGE
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    # According to https://docs.docker.com/engine/reference/commandline/tag/
    # the tag may contain lowercase and uppercase letters, digits, underscores,
    # periods, and hyphens, so we replace everything else by '_'. It cannot start
    # with a period or hyphen, so we replace those if we find them at the start of a line.
    # It must be no longer than 128 characters, so we truncate it in addition.
    #
    # tr -c means the same as --complement, but busybox tr doesn't have that
    - >
      IMAGE_TAG=$(
          echo -n "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" |
          tr -c '[:alnum:]_.-' '_' |
          sed 's/^[.-]/_/' |
          cut -c -128
      )
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/ci/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$IMAGE_TAG
      --force

package:controller-container-dev:
  stage: package
  needs:
    - build
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image:
    name: $KANIKO_IMAGE
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/ci/Dockerfile
      --destination $CI_REGISTRY_IMAGE:dev
      --force

trigger-docs:
  stage: trigger
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_NAME !~ /^.*canary$/
  trigger:
    project: opentalk/backend/docs

package:controller-container-tag:
  stage: package
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG != null
  image:
    name: $KANIKO_IMAGE
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/ci/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --force

package:read-latest-tag:
  stage: package
  needs: []
  rules:
    - if: $CI_COMMIT_TAG != null
  image:
    name: alpine/git
    entrypoint: ['']
  script:
    - git fetch --tags
    - LATEST_TAG=$(git tag --list | grep "^v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+$" | sort -V | tail -n1)
    - echo "LATEST_TAG=$LATEST_TAG" >> package.env
  artifacts:
    reports:
      dotenv: package.env

package:controller-container-latest:
  stage: package
  needs:
    - build
    - package:read-latest-tag
  rules:
    - if: $CI_COMMIT_TAG != null
  image:
    name: $KANIKO_IMAGE
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - |
      if [ "$CI_COMMIT_TAG" == "$LATEST_TAG" ]; then
        /kaniko/executor \
          --registry-mirror=mirror.gcr.io \
          --context $CI_PROJECT_DIR \
          --dockerfile $CI_PROJECT_DIR/ci/Dockerfile \
          --destination $CI_REGISTRY_IMAGE:latest \
          --force
      fi
