---
image: git.heinlein-video.de:5050/heinlein-video/rust:1.58

stages:
  - lint
  - test
  - build
  - package

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  # Enable one network per build for the test container and services
  FF_NETWORK_PER_BUILD: 'true'

lint:fmt:
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    # Run on feature branches
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  stage: lint
  script:
    - cargo fmt -- --check

lint:clippy:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  stage: lint
  script: cargo clippy --workspace --all-features --tests -- --deny warnings

lint:dependency_check:
  image: git.heinlein-video.de:5050/heinlein-video/cargo-deny:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  stage: lint
  script: cargo-deny check

lint:yaml:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  stage: lint
  image: archlinux:latest
  before_script:
    - pacman -Syy --noconfirm yamllint
  script: yamllint .

test:cargo_test:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  stage: test
  variables:
    # Set ENV vars for services
    POSTGRES_DB: k3k
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password123
    POSTGRES_HOST_AUTH_METHOD: trust
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_PORT: '5672'
    JANUS_EXCHANGE_TYPE: topic
    # Used for integration tests
    POSTGRES_BASE_URL: postgres://postgres:password123@postgres:5432
    DATABASE_NAME: k3k
    KUSTOS_TESTS_DATABASE_URL: postgres://postgres:password123@postgres:5432/kustos
    AMQP_ADDR: amqp://guest:guest@rabbitmq:5672
    REDIS_ADDR: redis://redis:6379/
  services:
    - name: postgres:13-alpine
      alias: postgres
    - name: rabbitmq:3.8
      alias: rabbitmq
    - name: quay.io/freswa/janus-gateway-rmq:latest
      alias: janus-gateway
    - name: redis:6-alpine
      alias: redis
  before_script:
    - rustup component add rustfmt
    - cargo install diesel_cli --no-default-features --features="barrel-migrations,barrel/pg,postgres"
  script:
    - cargo test --workspace --locked
    # Verify that the HEAD schema.rs matches the actual HEAD migration database schema.
    - RUST_LOG=error cargo xtask verify-db-schema --postgres-url="${POSTGRES_BASE_URL}"

build:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG != null
  stage: build
  artifacts:
    paths:
      - target/release/k3k-controller
    expire_in: 1 week
  before_script:
    - apt-get update && apt-get install -y libpq-dev musl-tools
  script:
    - cargo build --release --locked --workspace

package:controller-container:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG != null
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/ci/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --destination $CI_REGISTRY_IMAGE:latest
      --force
