image: "rust:latest"

services:
  - postgres:13-alpine

stages:
  - lint
  - test
  - build

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

  POSTGRES_DB: migration_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "password123"
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  key: $CI_JOB_STAGE
  paths:
  - .cargo/
  - target/

lint:fmt:
  stage: lint
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

lint:clippy:
  stage: lint
  before_script:
    - rustup component add clippy
  script: cargo clippy --all-features -- --deny warnings

lint:dependency_check:
  stage: lint
  before_script:
    - cargo install --locked cargo-deny
  script: cargo deny check

test:cargo_check:
  stage: test
  variables:
    RUSTFLAGS: "-D warnings"
  script: cargo check --tests --all-features

test:cargo_test:
  stage: test
  variables:
    DATABASE_URL: "postgres://postgres:password123@postgres:5432/migration_test"
  before_script:
    - rustup component add rustfmt
    - cargo install diesel_cli --no-default-features --features="barrel-migrations,barrel/pg,postgres"
  script:
    - cargo test
    - ./.cargo/bin/diesel print-schema | /usr/local/cargo/bin/rustfmt | diff src/db/schema.rs -

build:release:
  stage: build
  artifacts:
    paths:
      - target/release/k3k-controller
  script:
    - cargo build --release
