[package]
name = "k3k-controller"
version = "0.1.0"
authors = [
    "Konstanin Baltruschat <k.baltruschat@heinlein-video.de>",
    "Marvin Ankert <m.ankert@heinlein-video.de>"
]
edition = "2018"

[dependencies]

### Logging utilities
log = { version = "0.4", features = ["serde"] }
fern = "0.6"

### Config
config = { version = "0.11", default-features = false, features = ["toml"] }
serde = { version = "1", features = ["derive"] }

### Error handling
anyhow = "1.0"

### Database migrations
refinery = { version = "0.5", features = ["tokio-postgres", "tokio"] }
refinery-core = "0.5"
barrel = { version = "0.6", features = ["pg"] }

### Runtime
tokio = "1.5"
