[package]
name = "k3k-controller"
version = "0.1.0"
authors = [
    "Konstanin Baltruschat <k.baltruschat@heinlein-video.de>",
    "Marvin Ankert <m.ankert@heinlein-video.de>",
]
edition = "2018"

[workspace]
members = [
    "crates/janus-client",
    "crates/janus-media",
    "crates/automod",
    "crates/ee-chat",
    "crates/chat",
    "crates/controller",
    "crates/client",
    "crates/r3dlock",
]

[dependencies]
anyhow = "1.0"
actix-web = "4.0.0-beta.8"
controller = { path = "crates/controller", package = "k3k-controller-core" }
janus-media = { path = "crates/janus-media", package = "k3k-janus-media" }
automod = { path = "crates/automod", package = "k3k-automod" }
ee-chat = { path = "crates/ee-chat", package = "k3k-ee-chat" }
chat = { path = "crates/chat", package = "k3k-chat" }
