# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[workspace]
members = ["crates/*", "xtask"]

[workspace.package]
authors = ["OpenTalk Team <mail@opentalk.eu>"]
version = "0.0.0-dev"
