[package]
name = "k3k-controller"
version = "0.1.0"
authors = [
    "Konstanin Baltruschat <k.baltruschat@heinlein-video.de>",
    "Marvin Ankert <m.ankert@heinlein-video.de>"
]
edition = "2018"

[workspace]
members = [
    "client",
]

[dependencies]
### Logging utilities
log = { version = "0.4", features = ["serde"] }
fern = "0.6"

### Config
config = { version = "0.11", default-features = false, features = ["toml"] }
serde = { version = "1", features = ["derive"] }
structopt = "0.3"

### Error handling
anyhow = "1.0"
thiserror = "1.0"
validator = { version = "0.13", features = ["derive"] }

### Database ORM
diesel = { version = "1.4.6", features = ["postgres", "uuid", "uuidv07", "r2d2"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }

### Database migrations
refinery = { version = "0.5", features = ["tokio-postgres", "tokio"] }
refinery-core = "0.5"
diesel_migrations = "1.4"
barrel = { version = "0.6", features = ["pg"] }

### Web Framework & Runtime
tokio = "1"
tokio-stream = "0.1"
actix-web = { version = "4.0.0-beta.6", features = ["rustls"] }
actix-rt = "2.2"
# Until https://github.com/actix/actix-extras/pull/181 gets merged into the main branch use the forked version of actix-extras
actix-web-httpauth = { git = "https://github.com/nhruo123/actix-extras.git", rev = "b4e8db446843a99b06c7ec40f18ef7b59ee7e955" }
actix-cors = { git = "https://github.com/nhruo123/actix-extras.git", rev = "b4e8db446843a99b06c7ec40f18ef7b59ee7e955" }
futures-util = "0.3"
async-trait = "0.1"
futures = "0.3"
bytes = "1"
serde_json = "1"

### OpenID Connect & JWT
openidconnect = { version = "2.0", features = ["reqwest"] }
jsonwebtoken = "7"
base64 = "0.13"
chrono = "0.4"

### Websockets
async-tungstenite = "0.13"
actix-web-actors = { git = "https://github.com/actix/actix-web.git" }

# Rust Encryption
ring = "0.16"
rustls = "0.19"

[dev-dependencies]
k3k-controller-client = { path = "client"}
tokio-postgres = "0.7"
serial_test = "0.5"
regex = "1.5"
