[package]
name = "k3k-controller"
version = "0.1.0"
authors = [
    "Konstanin Baltruschat <k.baltruschat@heinlein-video.de>",
    "Marvin Ankert <m.ankert@heinlein-video.de>",
]
edition = "2018"

[workspace]
members = ["crates/*", "xtask"]

[dependencies]
anyhow = "1.0"
actix-web = { version = "4.0.0-beta.8", default-features = false }
controller = { path = "crates/controller", package = "k3k-controller-core" }
janus-media = { path = "crates/janus-media", package = "k3k-janus-media" }
automod = { path = "crates/automod", package = "k3k-automod" }
ee-chat = { path = "crates/ee-chat", package = "k3k-ee-chat" }
chat = { path = "crates/chat", package = "k3k-chat" }
legal-vote = { path = "crates/legal-vote", package = "k3k-legal-vote" }
polls = { path = "crates/polls", package = "k3k-polls" }
kustos = { path = "crates/kustos" }
