# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[workspace]
members = ["crates/*", "xtask"]
resolver = "2"

[workspace.package]
authors = ["OpenTalk Team <mail@opentalk.eu>"]
homepage = "https://opentalk.eu/"
repository = "https://gitlab.opencode.de/opentalk/controller"
version = "0.0.0-dev"

[workspace.dependencies]
kustos = { path = "crates/kustos", version = "0.0.0-dev" }
kustos-shared = { path = "crates/kustos-shared", version = "0.0.0-dev" }
opentalk-cache = { path = "crates/cache", version = "0.0.0-dev" }
opentalk-chat = { path = "crates/chat", version = "0.0.0-dev" }
opentalk-client = { path = "crates/client", version = "0.0.0-dev" }
opentalk-client-shared = { path = "crates/client-shared", version = "0.0.0-dev" }
opentalk-community-modules = { path = "crates/community-modules", version = "0.0.0-dev" }
opentalk-controller-core = { path = "crates/controller-core", version = "0.0.0-dev" }
opentalk-controller-settings = { path = "crates/controller-settings", version = "0.0.0-dev" }
opentalk-controller-utils = { path = "crates/controller-utils", version = "0.0.0-dev" }
opentalk-core = { path = "crates/core", version = "0.0.0-dev" }
opentalk-database = { path = "crates/database", version = "0.0.0-dev" }
opentalk-db-storage = { path = "crates/db-storage", version = "0.0.0-dev" }
opentalk-integration = { path = "crates/integration", version = "0.0.0-dev" }
opentalk-janus-media = { path = "crates/janus-media", version = "0.0.0-dev" }
opentalk-jobs = { path = "crates/jobs", version = "0.0.0-dev" }
opentalk-kustos-prefix = { path = "crates/kustos-prefix", version = "0.0.0-dev" }
opentalk-kustos-prefix-impl = { path = "crates/kustos-prefix-impl", version = "0.0.0-dev" }
opentalk-log = { path = "crates/log", version = "0.0.0-dev" }
opentalk-mail-worker-protocol = { path = "crates/mail-worker-protocol", version = "0.0.0-dev" }
opentalk-polls = { path = "crates/polls", version = "0.0.0-dev" }
opentalk-proc-macro-fields-helper = { path = "crates/proc-macro-fields-helper", version = "0.0.0-dev" }
opentalk-protocol = { path = "crates/protocol", version = "0.0.0-dev" }
opentalk-r3dlock = { path = "crates/r3dlock", version = "0.0.0-dev" }
opentalk-shared-folder = { path = "crates/shared-folder", version = "0.0.0-dev" }
opentalk-signaling-core = { path = "crates/signaling-core", version = "0.0.0-dev" }
opentalk-test-util = { path = "crates/test-util", version = "0.0.0-dev" }
opentalk-timer = { path = "crates/timer", version = "0.0.0-dev" }
opentalk-types = { path = "crates/types", version = "0.0.0-dev" }
opentalk-whiteboard = { path = "crates/whiteboard", version = "0.0.0-dev" }

actix-http = "3"
actix-rt = "2"
actix-web = { version = "4", default-features = true }
actix-web-httpauth = "0.8"
anstream = "0.6"
arc-swap = "1"
async-trait = "0.1"
aws-sdk-s3 = { version = "1.24.0", features = ["behavior-version-latest"] }
axum = "0.7"
base64 = "0.22"
bigdecimal = "0.4"
bincode = "1"
bytes = "1"
bytestring = "1"
chrono = "0.4"
chrono-tz = "0.9"
clap = { version = "4", features = ["derive"] }
config = { version = "0.14", default-features = false, features = ["toml"] }
derive_more = "1.0"
diesel = "2"
diesel-async = "0.5"
displaydoc = "0.2"
either = "1"
email_address = "0.2.4"
env_logger = "0.11"
futures = "0.3"
http = "0.2"
http-request-derive = "0.1.2"
itertools = "0.13"
lapin = { version = "2", default-features = false }
lapin-pool = "0.1"
log = "0.4"
md5 = "0.7"
openidconnect = "3"
opentalk-diesel-newtype = "0.12"
opentalk-etherpad-client = { version = "0.1.0", default-features = false, features = [
  "rustls-tls-native-roots",
] }
opentalk-janus-client = "0.3"
opentalk-keycloak-admin = { version = "0.2.1", default-features = false, features = [
  "rustls-tls-native-roots",
] }
opentalk-nextcloud-client = { version = "0.1.1", default-features = false, features = [
  "rustls-tls-native-roots",
] }
opentelemetry = { version = "0.24", default-features = false, features = [
  "metrics",
] }
owo-colors = "4"
parking_lot = "0.12"
percent-encoding = "2"
phonenumber = "0.3"
pretty_assertions = "1"
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
rand = "0.8"
redis = "0.25"
redis-args = "0.15"
reqwest = { version = "0.11", default-features = false }
rustc-hash = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
serde_urlencoded = "0.7"
serde_with = "3.8"
serial_test = "3"
snafu = "0.8"
strum = { version = "0.26", features = ["derive"] }
syn = "2"
tokio = "1"
tokio-stream = { version = "0.1", features = ["sync"] }
tracing = "0.1"
url = "2"
utoipa = "4"
utoipa-swagger-ui = "7"
uuid = "1"
validator = { version = "0.18", features = ["derive"] }

[workspace.dependencies.casbin]
default-features = false
git = "https://github.com/kbalt/casbin-rs.git"
rev = "fddb52d61385913727e24a5c7337eed489cb0d56"

[workspace.lints.clippy]
self_named_module_files = "deny"
