[package]
name = "k3k-controller"
version = "0.1.0"
authors = [
    "Konstanin Baltruschat <k.baltruschat@heinlein-video.de>",
    "Marvin Ankert <m.ankert@heinlein-video.de>"
]
edition = "2018"

[dependencies]

### Logging utilities
log = { version = "0.4", features = ["serde"] }
fern = "0.6"

### Config
config = { version = "0.11", default-features = false, features = ["toml"] }
serde = { version = "1", features = ["derive"] }

### Error handling
anyhow = "1.0"
thiserror = "1.0"

### Database ORM
diesel = { version = "1.4.6", features = ["postgres", "uuid", "uuidv07"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }

### Database migrations
refinery = { version = "0.5", features = ["tokio-postgres", "tokio"] }
refinery-core = "0.5"
diesel_migrations = "1.4"
barrel = { version = "0.6", features = ["pg"] }

### Web Framework & Runtime
actix-web = "4.0.0-beta.6"
actix-rt = "2.2"
# Until https://github.com/actix/actix-extras/pull/181 gets merged into the main branch use the forked version of actix-extras
actix-web-httpauth = { git = "https://github.com/nhruo123/actix-extras.git", rev = "b4e8db446843a99b06c7ec40f18ef7b59ee7e955" }
actix-cors = { git = "https://github.com/nhruo123/actix-extras.git", rev = "b4e8db446843a99b06c7ec40f18ef7b59ee7e955" }

### OpenID Connect & JWT
openidconnect = { version = "2.0", features = ["reqwest"] }
jsonwebtoken = "7"
base64 = "0.13"
chrono = "0.4"

[dev-dependencies]
# JWT Testing to create signatures
ring = "0.16"
