# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

FROM rust:slim-bookworm AS builder
RUN mkdir /app
WORKDIR /app

ADD . /app

RUN apt-get update && apt-get install --no-install-recommends -y libpq-dev protobuf-compiler curl

RUN cargo build --release --locked

FROM debian:bookworm-slim

RUN apt-get update && apt-get full-upgrade -y && \
    apt-get install --no-install-recommends -y libpq5 ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV USERID=1000
ENV GROUPID=1000

RUN mkdir /app
WORKDIR /app

COPY --from=builder /app/target/release/opentalk-controller .
RUN ln -s /app/opentalk-controller /app/k3k-controller
COPY extra/example.toml /app/config.toml

USER $USERID:$GROUPID

EXPOSE 11311
ENTRYPOINT [ "/app/opentalk-controller" ]
