# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

SPDX-PackageDownloadLocation = "https://git.opentalk.dev/opentalk/backend/controller"
SPDX-PackageName = "OpenTalk Controller"
SPDX-PackageSupplier = "OpenTalk GmbH <mail@opentalk.eu>"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "OpenTalk GmbH <mail@opentalk.eu>"
SPDX-License-Identifier = "EUPL-1.2"
path = [
  ".commitlintrc.json",
  ".gitlab/issue_templates/**.md",
  "CHANGELOG.md",
  "Cargo.lock",
  "api/**.md",
  "api/**.yaml",
  "ci/spectral/**.yml",
  "crates/**/README.md",
  "crates/opentalk-db-storage/src/migrations/**.sql",
  "crates/opentalk-db-storage/src/schema.rs",
  "crates/opentalk-signaling-module-meeting-report/src/*.typ",
  "docs/**.md",
  "docs/**.yml",
  "renovate.json",
]
precedence = "aggregate"
