# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-controller-core"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false
build = "build.rs"

[dependencies]
controller-settings = { path = "../controller-settings", package = "opentalk-controller-settings" }
database = { path = "../database", package = "opentalk-database" }
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
mail-worker-proto = { path = "../mail-worker-protocol", package = "opentalk-mail-worker-protocol", features = [
    "client",
] }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }

### Logging utilities
log = { version = "0.4", features = ["serde"] }
tracing = { version = "0.1" }
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = [
    "parking_lot",
    "env-filter",
] }
tracing-opentelemetry = "0.18"
opentelemetry = { version = "0.18", default-features = false, features = [
    "trace",
    "rt-tokio-current-thread",
    "metrics",
] }
opentelemetry-otlp = "0.11"
opentelemetry-prometheus = "0.11"
prometheus = "0.13"
tracing-actix-web = { version = "0.7" }

### Config
config = { version = "0.13.3", default-features = false, features = ["toml"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
arc-swap = "1.6"

### Error handling
anyhow = "1.0"
thiserror = "1.0"
validator = { version = "0.16", features = ["derive"] }

### Database ORM
diesel = { version = "2", features = [
    "postgres",
    "uuid",
    "serde_json",
    "chrono",
] }
diesel-async = "0.2.0"
uuid = { package = "uuid", version = "1.3.0", features = ["serde", "v4"] }

### S3 Storage
aws-config = "0.51"
aws-sdk-s3 = "0.21"

### Web Framework & Runtime
tokio = { version = "1", features = ["signal"] }
tokio-stream = { version = "0.1.12", features = ["sync"] }
actix-web = { version = "4", features = ["rustls"] }
actix-rt = "2.8"
actix-web-httpauth = "0.8"
actix-cors = "0.6"
futures-util = "0.3"
async-trait = "0.1"
futures = "0.3"
bytes = "1"
serde_json = "1"
bincode = "1.3"
parking_lot = "0.12"
mime = "0.3.16"
bytestring = { version = "1", features = ["serde"] }

### RabbitMQ
lapin = { version = "2", default-features = false }
lapin-pool = { path = "../lapin-pool" }

### Redis
redis = { version = "0.22", features = ["tokio-comp", "connection-manager"] }
url = "2"
r3dlock = { path = "../r3dlock" }

### OpenID Connect & JWT
openidconnect = { version = "2" }
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
] }
jsonwebtoken = "8.3.0"
base64 = "0.13"
chrono = "0.4"
chrono-tz = { version = "0.6", features = ["serde"] }

### Websockets
actix = "0.13"
actix-http = "3"
actix-web-actors = "4.2"

### Rust Encryption
ring = "0.16"
rustls = "0.20"
rustls-pemfile = "1.0"
md5 = "0.7"

### QoL/Util
either = "1.8.1"
itertools = "0.10"
phonenumber = "0.3"
email_address = "0.2.4"
redis-args = { path = "../redis-args", package = "opentalk-redis-args" }
slotmap = "1"
rustc-hash = "1.1"

# Random Distributions etc. Used for RR
rand = "0.8.5"

### Reload controller process
sysinfo = { version = "0.28", default-features = false }
nix = "0.26"

### Access Control
kustos = { path = "../kustos" }
keycloak-admin = { path = "../keycloak-admin" }
regex = "1.7"

rrule = "0.7"

### CLI
tabled = "0.10"

[dev-dependencies]
test-util = { path = "../test-util", package = "opentalk-test-util", features = ["database"] }
pretty_assertions = "1.3"

[build-dependencies]
anyhow = "1.0"
vergen = { version = "7.5", default-features = false, features = [
    "build",
    "cargo",
    "rustc",
    "git",
] }
