# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-timer"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
log.workspace = true
redis-args.workspace = true
redis.workspace = true
serde.workspace = true
opentalk-signaling-core.workspace = true
tokio.workspace = true
tracing.workspace = true
opentalk-types = { workspace = true, features = ["backend"] }
uuid.workspace = true

[dev-dependencies]
opentalk-test-util = { workspace = true, features = ["controller"] }
pretty_assertions.workspace = true
serial_test.workspace = true
actix-rt.workspace = true
