# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "k3k-timer"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
controller = { path = "../controller", package = "k3k-controller-core" }
controller-shared = { path = "../controller-shared-types", package = "k3k-controller-shared" }
serde = { version = "1", features = ["derive"] }
redis = "0.21"
redis-args = { path = "../redis-args", package = "k3k-redis-args" }

[dev-dependencies]
test-util = { path = "../test-util", package = "k3k-test-util", features = ["controller"] }
pretty_assertions = "1.3"
serial_test = "0.7"
actix-rt = "2.2"
