# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-timer"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
controller = { path = "../controller", package = "opentalk-controller-core" }
controller-settings = { path = "../controller-settings", package = "opentalk-controller-settings" }
serde.workspace = true
redis.workspace = true
redis-args = { path = "../redis-args", package = "opentalk-redis-args" }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }

[dev-dependencies]
test-util = { path = "../test-util", package = "opentalk-test-util", features = ["controller"] }
pretty_assertions.workspace = true
serial_test.workspace = true
actix-rt = "2.8"
