# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-chat"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
controller = { path = "../controller", package = "opentalk-controller-core" }
controller-shared = { path = "../controller-shared-types", package = "opentalk-controller-shared" }
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
database = { path = "../database", package = "opentalk-database" }
serde = { version = "1", features = ["derive"] }
redis = "0.22"
redis-args = { path = "../redis-args", package = "opentalk-redis-args" }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }

[dev-dependencies]
pretty_assertions = "1.3"
serial_test = "1"
test-util = { path = "../test-util", package = "opentalk-test-util", features = ["controller"]}
actix-rt = "2.8"
