# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-chat"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
controller = { path = "../controller", package = "opentalk-controller-core" }
controller-settings = { path = "../controller-settings", package = "opentalk-controller-settings" }
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
database = { path = "../database", package = "opentalk-database" }
serde.workspace = true
redis.workspace = true
redis-args = { path = "../redis-args", package = "opentalk-redis-args" }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }

[dev-dependencies]
pretty_assertions.workspace = true
serial_test.workspace = true
test-util = { path = "../test-util", package = "opentalk-test-util", features = ["controller"]}
actix-rt = "2.8"
