# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Signaling types and traits for OpenTalk"
documentation = "https://docs.rs/opentalk-types-signaling"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-types-signaling"
publish = true
repository.workspace = true
version.workspace = true

[features]

[dependencies]
