---
openapi: 3.0.3
info:
  title: OpenTalk Controller Frontend API
  description: Specifies the endpoints and structure of the OpenTalk Controller Frontend API
  contact:
    name: OpenTalk Team
    email: mail@opentalk.eu
  license:
    name: EUPL-1.2
  version: 0.0.0-dev
servers:
  - url: /v1
paths:
  /auth/login:
    get:
      tags:
        - "api::v1::auth"
      summary: Get the configured OIDC provider
      description: |
        Returns the relevant information for a frontend to authenticate against the
        configured OIDC provider for the OpenTalk service.
      operationId: get_login
      responses:
        "200":
          description: Get information about the OIDC provider
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetLoginResponse"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security: []
    post:
      tags:
        - "api::v1::auth"
      summary: The login endpoint
      description: |
        Attempt to authenticate with a provided ID token. The ID token can be
        received from an OIDC provider and contains information about the requesting
        user as well as an expiration timestamp. When a valid token with an unknown user
        is provided, a new user will be created in the database.
      operationId: post_login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostLoginRequestBody"
        required: true
      responses:
        "200":
          description: "Login successful, answer contains a list of permissions"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostLoginResponse"
              example:
                permissions: []
        "400":
          description: The provided ID token is malformed or contains invalid claims
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBody"
              example:
                code: invalid_claims
                message: some required attributes are missing or malformed
        "401":
          description: The provided ID token is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBody"
              example:
                code: unauthorized
                message: Authentication failed
        "500":
          $ref: "#/components/responses/InternalServerError"
      security: []
  /users/me:
    get:
      tags:
        - "api::v1::users"
      summary: "Get the current user's profile"
      description: |
        Returns the private user profile of the currently logged-in user. This
        private profile contains information that is not visible in the public
        profile, such as tariff status or the used storage.
      operationId: get_me
      responses:
        "200":
          description: Information about the logged in user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrivateUserProfile"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - BearerAuth: []
components:
  schemas:
    ErrorBody:
      oneOf:
        - $ref: "#/components/schemas/StandardErrorBody"
        - $ref: "#/components/schemas/ValidationErrorBody"
      description: The body of an error response
    GetLoginResponse:
      type: object
      description: "Body of the response to a *GET* request on `/auth/login`"
      required:
        - oidc
      properties:
        oidc:
          $ref: "#/components/schemas/OidcProvider"
    OidcProvider:
      type: object
      description: Represents an OIDC provider
      required:
        - name
        - url
      properties:
        name:
          type: string
          description: The name of the provider
        url:
          type: string
          description: The url of the provider
    PostLoginRequestBody:
      type: object
      description: "Body of a *POST* request on `/auth/login`"
      required:
        - id_token
      properties:
        id_token:
          type: string
          description: The id token to use for the login
          example: bG9yZW0gaXBzdW0sIHF1aWEgZG9sb3Igc2
    PostLoginResponse:
      type: object
      description: "Body of the response to a *POST* request on `/auth/login`"
      required:
        - permissions
      properties:
        permissions:
          type: array
          items:
            type: string
          description: Permissions is a set of strings that each define a permission a user has.
          uniqueItems: true
    PrivateUserProfile:
      type: object
      description: |
        Private user profile.
        
        Similar to [`PublicUserProfile`], but contains additional "private" information about a user.
        Is only accessible to the user himself.
        Is used on */users/me* endpoints.
      required:
        - id
        - email
        - title
        - firstname
        - lastname
        - display_name
        - avatar_url
        - dashboard_theme
        - conference_theme
        - language
        - tariff_status
        - used_storage
      properties:
        avatar_url:
          type: string
          description: "The user's avatar URL"
        conference_theme:
          type: string
          description: The conference theme
        dashboard_theme:
          type: string
          description: The dashboard theme
        display_name:
          type: string
          description: "The user's display name"
        email:
          type: string
          description: The email of the user
        firstname:
          type: string
          description: "The user's first name"
        id:
          $ref: "#/components/schemas/UserId"
        language:
          type: string
          description: The language for the user
        lastname:
          type: string
          description: "The user's last name"
        tariff_status:
          $ref: "#/components/schemas/TariffStatus"
        title:
          type: string
          description: The title of the user
        used_storage:
          type: integer
          format: int64
          description: "The user's used storage"
          minimum: 0
    StandardErrorBody:
      type: object
      description: Standard API error body
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Machine readable error code
        message:
          type: string
          description: Human readable message
    TariffStatus:
      type: string
      enum:
        - default
        - paid
        - downgraded
    UserId:
      type: string
      format: uuid
      description: The id of a user
    ValidationErrorBody:
      type: object
      description: The body of a validation error response
      required:
        - code
        - message
        - errors
      properties:
        code:
          type: string
          description: Machine readable error message
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorEntry"
          description: A list validation errors
        message:
          type: string
          description: Human readable message
    ValidationErrorEntry:
      type: object
      description: An entry in a validation error list
      required:
        - code
      properties:
        code:
          type: string
          description: Machine readable error message
        field:
          type: string
          description: |
            The field related to the error
            
            If the value is [`None`] that means the error happened at struct level
          nullable: true
        message:
          type: string
          description: Human readable error message
          nullable: true
  responses:
    InternalServerError:
      description: An internal server error occurred
    Unauthorized:
      description: |
        The provided access token is expired or the provided id or access token is invalid.
                The WWW-Authenticate header will contain an error description 'session expired' to distinguish between
                an invalid and an expired token
      headers:
        www-authenticate:
          schema:
            type: string
          description: |
            
            Will contain 'session expired' to distinguish between an invalid and an expired token.
            
            Examples:
            
                Bearer error="invalid_token", error_description="The provided access token is invalid"
                Bearer error="invalid_request", error_description="The user session expired"
      content:
        application/json:
          schema:
            type: object
            description: Internal reusable dummy type for utoipa unauthorized error
            required:
              - code
              - message
            properties:
              code:
                type: string
                description: Machine readable error code
              message:
                type: string
                description: Human readable message
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
tags:
  - name: "api::v1::auth"
    description: Endpoints related to authentication
  - name: "api::v1::invites"
    description: Endpoints related to meeting invites
  - name: "api::v1::rooms"
    description: Endpoints related to meeting rooms
  - name: "api::v1::assets"
    description: Endpoints related to file assets
  - name: "api::v1::sip_configs"
    description: Endpoints related to SIP configuration
  - name: "api::v1::services::recording"
    description: Endpoints related to the meeting recording service
  - name: "api::v1::turn"
    description: Endpoints related TURN server usage
  - name: "api::v1::users"
    description: Endpoints related to user information and management