# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "redis-args"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = true
description = "Derive macro for reading and writing types for redis usage, either through serde or format args"

[dependencies]
redis-args-impl = { path = "../redis-args-impl" }
redis.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde.workspace = true
