# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Derive macro for reading and writing types for redis usage, either through serde or format args"
documentation = "https://docs.rs/redis-args"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "redis-args"
publish = true
repository.workspace = true
version.workspace = true

[dependencies]
redis.workspace = true
redis-args-impl.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde.workspace = true
