# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-redis-args"
edition = "2021"
authors.workspace = true
version.workspace = true
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["extra-traits"] }
proc-macro2 = "1"

[dev-dependencies]
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
