# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "k3k-whiteboard"
version = "1.0.0-rc.10"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
controller-shared = { path = "../controller-shared-types", package = "k3k-controller-shared" }
controller = { path = "../controller", package = "k3k-controller-core" }
db-storage = { path = "../db-storage", package = "k3k-db-storage" }
database = { path = "../database", package = "k3k-database" }
redis = "0.21"
redis-args = { path = "../redis-args", package = "k3k-redis-args" }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "cookies",
    "rustls-tls",
    "stream",
] }
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
serde_json = "1"
anyhow = "1.0"
tokio = { version = " 1", features = ["time"] }
chrono = "0.4"
percent-encoding = "2.1"
url = "2.2"
bytes = "1.1"
futures = "0.3"

[dev-dependencies]
actix-rt = "2.2"
rand = "0.8"
