# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-whiteboard"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
controller-settings = { path = "../controller-settings", package = "opentalk-controller-settings" }
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
database = { path = "../database", package = "opentalk-database" }
log.workspace = true
redis.workspace = true
redis-args = { path = "../redis-args", package = "opentalk-redis-args" }
signaling-core = { path = "../signaling-core", package = "opentalk-signaling-core" }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }
reqwest = { workspace = true, features = [
    "json",
    "cookies",
    "rustls-tls-native-roots",
    "stream",
] }
serde.workspace =  true
serde_repr.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["time"] }
chrono.workspace = true
percent-encoding.workspace = true
url.workspace = true
bytes.workspace = true
futures.workspace = true
async-trait.workspace = true
tracing.workspace = true

[dev-dependencies]
actix-rt.workspace = true
rand.workspace = true
