# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-whiteboard"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
controller-settings = { path = "../controller-settings", package = "opentalk-controller-settings" }
controller = { path = "../controller", package = "opentalk-controller-core" }
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
database = { path = "../database", package = "opentalk-database" }
redis.workspace = true
redis-args = { path = "../redis-args", package = "opentalk-redis-args" }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }
reqwest = { workspace = true, features = [
    "json",
    "cookies",
    "rustls-tls-native-roots",
    "stream",
] }
serde.workspace =  true
serde_repr = "0.1"
serde_json.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["time"] }
chrono.workspace = true
percent-encoding = "2.2"
url.workspace = true
bytes.workspace = true
futures.workspace = true

[dev-dependencies]
actix-rt = "2.8"
rand.workspace = true
