# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-whiteboard"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
log.workspace = true
opentalk-controller-settings.workspace = true
opentalk-database.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types = { workspace = true, features = ["backend"] }
redis-args.workspace = true
redis.workspace = true
reqwest = { workspace = true, features = [
    "json",
    "cookies",
    "rustls-tls-native-roots",
    "stream",
] }
serde.workspace =  true
tracing.workspace = true
url.workspace = true
