# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "r3dlock"
version = "0.1.0"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
publish = false

[dependencies]
redis = { workspace = true, features = ["tokio-comp"] }
tokio = { workspace = true, features = ["time"] }

rand.workspace = true
thiserror.workspace = true
displaydoc.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
tokio = { workspace = true, features = ["macros", "test-util"] }
