# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
default-run = "opentalk-controller"
edition = "2021"
license = "EUPL-1.2"
name = "opentalk-controller"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
actix-web.workspace = true
opentalk-controller-core.workspace = true
opentalk-controller-service.workspace = true
opentalk-signaling-modules.workspace = true

[features]
default = ["swagger"]
swagger = ["opentalk-controller-core/swagger"]
