# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2021"
license = "EUPL-1.2"
name = "opentalk-mail-worker-protocol"
publish = false
version.workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
opentalk-db-storage = { workspace = true, optional = true }
opentalk-keycloak-admin = { workspace = true, optional = true }
opentalk-types.workspace = true
serde.workspace = true
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
pretty_assertions.workspace = true
serde_json.workspace = true

[features]
client = ["dep:opentalk-db-storage", "dep:opentalk-keycloak-admin"]
default = []
