# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2021"
license = "EUPL-1.2"
name = "opentalk-mail-worker-protocol"
publish = false
version.workspace = true

[dependencies]
chrono = { workspace = true }
opentalk-types.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }
uuid = { workspace = true }

[dev-dependencies]
pretty_assertions.workspace = true
serde_json.workspace = true

[features]
client = ["serde"]
default = ["serde"]
serde = ["chrono/serde", "dep:serde", "uuid/serde"]
