# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-mail-worker-protocol"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
serde.workspace = true
uuid = { workspace = true, features = ["serde"] }
chrono = { workspace = true, features = ["serde"] }
opentalk-db-storage = { workspace = true, optional = true }
opentalk-keycloak-admin = { workspace = true, optional = true }
opentalk-types.workspace = true

[dev-dependencies]
serde_json.workspace = true
pretty_assertions.workspace = true

[features]
default = []
client = ["dep:opentalk-db-storage", "dep:opentalk-keycloak-admin"]
