# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2021"
license = "EUPL-1.2"
name = "opentalk-signaling-core"
publish = false
version.workspace = true

[dependencies]
reqwest.workspace = true
anyhow.workspace = true
actix-http.workspace = true
actix-rt = { workspace = true, optional = true }
async-trait.workspace = true
aws-sdk-s3.workspace = true
bigdecimal.workspace = true
bytes.workspace = true
bytestring.workspace = true
futures.workspace = true
kustos.workspace = true
lapin-pool.workspace = true
lapin.workspace = true
log.workspace = true
opentalk-controller-settings.workspace = true
opentalk-database.workspace = true
opentalk-db-storage.workspace = true
opentalk-r3dlock.workspace = true
opentalk-types = { workspace = true, features = ["backend"] }
opentelemetry = { workspace = true, features = ["metrics", "trace"] }
redis = { workspace = true, features = ["connection-manager", "tokio-comp"] }
redis-args.workspace = true
rustc-hash.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
slotmap = "1"
snafu.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid = { workspace = true, features = ["v4"] }

[features]
default = []
module_tester = ["actix-rt"]
