# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-signaling-core"
edition = "2021"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
aws-sdk-s3 = "0.21"
bytes.workspace = true
controller-settings = { path = "../controller-settings", package = "opentalk-controller-settings" }
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
diesel.workspace = true
futures.workspace = true
log.workspace = true
serde = { workspace = true, features = ["derive"] }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }

[dev-dependencies]
pretty_assertions.workspace = true
