# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-signaling-core"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
actix-rt = { workspace = true, optional = true }
actix-http.workspace = true
anyhow.workspace = true
async-trait.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-http = "0.55"
aws-smithy-types = "0.55"
bytes.workspace = true
bytestring.workspace = true
controller-settings = { path = "../controller-settings", package = "opentalk-controller-settings" }
database = { path = "../database", package = "opentalk-database" }
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
futures.workspace = true
kustos = { path = "../../crates/kustos" }
lapin.workspace = true
lapin-pool = { path = "../lapin-pool" }
log.workspace = true
opentelemetry = { workspace = true, features = [
    "trace",
    "rt-tokio-current-thread",
    "metrics",
] }
r3dlock = { path = "../r3dlock" }
redis = { workspace = true, features = ["tokio-comp", "connection-manager"] }
redis-args = { path = "../redis-args" }
rustc-hash.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
slotmap = "1"
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
types = { path = "../types", package = "opentalk-types", features = ["backend"] }
url.workspace = true
uuid = { workspace = true, features = ["v4"] }

[features]
default = []
module_tester = ["actix-rt"]
