[package]
name = "k3k-janus-media"
version = "1.0.0-rc.5"
edition = "2018"
publish = false
authors = ["OpenTalk Team <we@opentalk.eu>"]

[dependencies]
controller = { path = "../controller", package = "k3k-controller-core" }
controller-shared = { path = "../controller-shared-types", package = "k3k-controller-shared" }
serde = { version = "1", features = ["derive"] }
janus-client = { path = "../janus-client" }

[dev-dependencies]
test-util = { path = "../test-util", package = "k3k-test-util" }
