[package]
name = "k3k-janus-media"
version = "0.1.0"
edition = "2018"


[dependencies]
controller = { path = "../controller", package = "k3k-controller-core" }
serde = { version = "1", features = ["derive"] }
janus-client = { path = "../janus-client" }
