[package]
name = "k3k-janus-media"
version = "0.1.0"
edition = "2018"


[dependencies]
controller = { path = "../controller", package = "k3k-controller-core" }
controller-shared = { path = "../controller-shared-types", package = "k3k-controller-shared" }
serde = { version = "1", features = ["derive"] }
janus-client = { path = "../janus-client" }

[dev-dependencies]
test-util = { path = "../test-util", package = "k3k-test-util" }
