[package]
name = "k3k-automod"
version = "0.1.0"
edition = "2018"

[dependencies]
controller = { path = "../controller", package = "k3k-controller-core" }
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
rand = "0.8"

[dev-dependencies]
serial_test = "0.5"
