# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
default-run = "opentalk-controller"
name = "opentalk-controller"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
actix-web.workspace = true
anstream.workspace = true
opentalk-community-modules.workspace = true
opentalk-controller-core.workspace = true
owo-colors.workspace = true
