# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "OpenTalk report generation functionality"
documentation = "https://docs.rs/opentalk-report-generation"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-report-generation"
publish = true
repository.workspace = true
version.workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
chrono-tz.workspace = true
ecow = "0.2.3"
log.workspace = true
pretty_assertions.workspace = true
serde.workspace = true
snafu.workspace = true
typst = "0.12.0"
typst-kit = { version = "0.12.0", default-features = false, features = [
  "embed-fonts",
] }
typst-pdf = "0.12.0"

[dev-dependencies]
serde_json.workspace = true
