# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
build = "build.rs"
edition = "2021"
license = "EUPL-1.2"
name = "opentalk-controller-core"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
actix = "0.13"
actix-cors = "0.7"
actix-http = { version = "3", features = ["rustls-0_23"] }
actix-rt.workspace = true
actix-web = { workspace = true, features = ["rustls-0_23"] }
actix-web-actors = "4.3"
actix-web-httpauth.workspace = true
async-trait.workspace = true
base64.workspace = true
bytes.workspace = true
bytestring = { workspace = true, features = ["serde"] }
chrono.workspace = true
clap.workspace = true
diesel-async.workspace = true
either.workspace = true
futures.workspace = true
http.workspace = true
itertools.workspace = true
kustos.workspace = true
lapin-pool.workspace = true
log = { workspace = true, features = ["serde"] }
md5.workspace = true
mime = "0.3"
nix = { version = "0.29", features = ["signal"] }
openidconnect.workspace = true
opentalk-cache.workspace = true
opentalk-controller-service.workspace = true
opentalk-controller-service-facade.workspace = true
opentalk-controller-settings.workspace = true
opentalk-controller-utils.workspace = true
opentalk-database.workspace = true
opentalk-db-storage.workspace = true
opentalk-jobs.workspace = true
opentalk-keycloak-admin.workspace = true
opentalk-r3dlock.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types-api-v1 = { workspace = true, features = ["backend"] }
opentalk-types-common = { workspace = true, features = [
  "actix",
  "backend",
  "clap",
] }
opentalk-types-signaling = { workspace = true, features = ["backend"] }
opentalk-types-signaling-breakout = { workspace = true, features = ["backend"] }
opentalk-types-signaling-control = { workspace = true, features = ["backend"] }
opentalk-types-signaling-moderation = { workspace = true, features = [
  "backend",
] }
opentalk-types-signaling-recording = { workspace = true, features = [
  "backend",
] }
opentalk-types-signaling-recording-service = { workspace = true, features = [
  "backend",
] }
opentalk-version.workspace = true
opentelemetry = { workspace = true, features = ["metrics", "trace"] }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }
opentelemetry-prometheus.workspace = true
opentelemetry_sdk = { workspace = true, features = [
  "metrics",
  "rt-tokio-current-thread",
  "spec_unstable_metrics_views",
] }
phonenumber.workspace = true
prometheus.workspace = true
rand.workspace = true
redis = { workspace = true, features = ["connection-manager", "tokio-comp"] }
ring = "0.17"
rustls = "0.23"
rustls-pemfile = "2.0"
rustls-pki-types = "1.3"
serde.workspace = true
serde_json.workspace = true
service-probe = "0.2"
snafu.workspace = true
strum.workspace = true
sysinfo = { version = "0.34", default-features = false, features = ["system"] }
tabled = "0.18"
tokio = { workspace = true, features = ["signal"] }
tokio-stream.workspace = true
tracing.workspace = true
tracing-actix-web = { version = "0.7" }
tracing-futures = "0.2"
tracing-opentelemetry.workspace = true
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "parking_lot",
] }
url.workspace = true
utoipa = { workspace = true, features = ["actix_extras"] }
utoipa-swagger-ui = { workspace = true, features = [
  "actix-web",
], optional = true }
uuid = { workspace = true, features = ["serde", "v4"] }
yaml-rust2.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rand_chacha.workspace = true

[build-dependencies]
opentalk-version.workspace = true
snafu.workspace = true

[features]
default = []
swagger = ["dep:utoipa-swagger-ui"]
# is used inside macros from opentelemetry, provides internal
# logging for the OpenTelemetry library via tracing
internal-logs = []
