[package]
name = "k3k-test-util"
version = "0.1.0"
edition = "2018"

[dependencies]
controller = { path = "../controller", package = "k3k-controller-core" }
diesel = { version = "1.4.6", features = [
    "postgres",
    "uuid",
    "uuidv07",
    "r2d2",
    "serde_json",
] }
fern = "0.6"
