# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-test-util"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
log.workspace = true
redis.workspace = true
serde_json.workspace = true
tokio.workspace = true
diesel = { workspace = true, features = [
    "serde_json",
] }
diesel-async = { workspace = true, features = ["postgres", "deadpool"] }

fern = "0.6"
pretty_assertions.workspace = true

kustos = { workspace = true, optional = true }
opentalk-database = { workspace = true, optional = true }
opentalk-db-storage = { workspace = true, optional = true }
opentalk-signaling-core = { workspace = true, features = ["module_tester"] }
opentalk-types = { workspace = true, features = ["backend"] }

[dev-dependencies]
serde.workspace = true

[features]
controller = ["database", "dep:kustos"]
database = ["dep:opentalk-database", "dep:opentalk-db-storage"]

[package.metadata.cargo-machete]
ignored = [
  # is used in doctests
  "serde",
]
