# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-test-util"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { version = "1" }
diesel = { version = "2", features = [
    "uuid",
    "serde_json",
] }
diesel-async = { version = "0.2.1", features = ["postgres", "deadpool"] }

fern = "0.6"
pretty_assertions = "1.3"

controller = { path = "../controller", package = "opentalk-controller-core", optional = true }
controller-settings = { path = "../controller-settings", package = "opentalk-controller-settings", optional = true }
kustos = { path = "../kustos", package = "kustos", optional = true }
database = { path = "../database", package = "opentalk-database", optional = true }
db-storage = { path = "../db-storage", package = "opentalk-db-storage", optional = true }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }

[features]
controller = ["database", "dep:controller", "dep:controller-settings", "dep:kustos"]
database = ["dep:database", "dep:db-storage"]

