# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Signaling types for the OpenTalk recording_service module"
documentation = "https://docs.rs/opentalk-types-signaling-recording-service"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-types-signaling-recording-service"
publish = true
repository.workspace = true
version.workspace = true

[features]
backend = ["opentalk-types-common/backend", "serde"]
frontend = ["opentalk-types-common/frontend", "serde"]
serde = ["dep:serde", "opentalk-types-common/serde"]

[dependencies]
opentalk-types-common.workspace = true
serde = { workspace = true, optional = true }
