# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Signaling types for the OpenTalk recording_service module"
documentation = "https://docs.rs/opentalk-types-signaling-recording-service"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-types-signaling-recording-service"
publish = true
repository.workspace = true
version.workspace = true

[features]
backend = [
  "opentalk-types-common/backend",
  "opentalk-types-signaling-recording/backend",
  "serde",
]
frontend = [
  "opentalk-types-common/frontend",
  "opentalk-types-signaling-recording/frontend",
  "serde",
]
serde = [
  "dep:serde",
  "opentalk-types-common/serde",
  "opentalk-types-signaling-recording/serde",
  "url/serde",
]

[dependencies]
opentalk-types-common.workspace = true
opentalk-types-signaling-recording.workspace = true
serde = { workspace = true, optional = true }
url.workspace = true
