# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-types"
edition = "2021"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
actix-http = { workspace = true, optional = true }
actix-web-httpauth = { workspace = true, optional = true }
base64 = { workspace = true, optional = true }
bincode = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
chrono.workspace = true
chrono-tz.workspace = true
clap = { workspace = true, optional = true }
derive_more = "0.99"
diesel = { workspace = true, features = ["uuid", "postgres"], optional = true }
email_address.workspace = true
kustos = { path = "../kustos", optional = true }
rand = { workspace = true, optional = true }
redis = { workspace = true, optional = true }
redis-args = { path = "../redis-args", optional = true }
serde = { workspace = true, optional = true }
serde_json.workspace = true
thiserror.workspace = true
strum.workspace = true
uuid.workspace = true
validator = { workspace = true, optional = true }
url.workspace = true

[features]
default = ["frontend"]
actix = ["dep:actix-http", "dep:actix-web-httpauth", "dep:bytes"]
backend = ["actix", "diesel", "kustos", "rand", "redis", "serde"]
clap = ["dep:clap"]
diesel = ["serde", "dep:diesel"]
frontend = ["serde"]
kustos = ["dep:kustos"]
rand = ["dep:rand", "uuid/v4"]
redis = ["serde", "dep:redis", "dep:redis-args"]
serde = [
  "dep:base64",
  "dep:bincode",
  "dep:serde",
  "dep:validator",
  "chrono/serde",
  "chrono-tz/serde",
  "url/serde",
  "uuid/serde",
]

[dev-dependencies]
pretty_assertions.workspace = true
