# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-types"
edition = "2021"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
chrono.workspace = true
chrono-tz.workspace = true
derive_more = "0.99"
diesel = { workspace = true, features = ["uuid", "postgres"], optional = true }
kustos = { path = "../kustos", optional = true }
rand = { workspace = true, optional = true }
redis = { workspace = true, optional = true }
redis-args = { path = "../redis-args", package = "opentalk-redis-args", optional = true }
serde = { workspace = true, optional = true }
serde_json.workspace = true
thiserror.workspace = true
strum.workspace = true
uuid.workspace = true
validator = { workspace = true, optional = true }
url.workspace = true

[features]
default = ["frontend"]
backend = ["diesel", "kustos", "rand", "redis", "serde"]
diesel = ["serde", "dep:diesel"]
frontend = ["serde"]
kustos = ["dep:kustos"]
rand = ["dep:rand", "uuid/v4"]
redis = ["serde", "dep:redis", "dep:redis-args"]
serde = [
  "dep:serde",
  "dep:validator",
  "chrono/serde",
  "chrono-tz/serde",
  "url/serde",
  "uuid/serde",
]

[dev-dependencies]
pretty_assertions.workspace = true
