# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-types"
edition = "2021"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
chrono = "0.4"
chrono-tz = { version = "0.6" }
derive_more = "0.99"
diesel = { version = "2", features = ["postgres", "uuid"], optional = true }
kustos = { path = "../kustos", optional = true }
rand = { version = "0.8.5", optional = true }
redis = { version = "0.22", optional = true }
redis-args = { path = "../redis-args", package = "opentalk-redis-args", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
strum = { version = "0.24", features = ["derive"] }
uuid = { version = "1" }
validator = { version = "0.16", features = ["derive"], optional = true }

[features]
default = ["frontend"]
backend = ["diesel", "kustos", "rand", "redis", "serde"]
diesel = ["serde", "dep:diesel"]
frontend = ["serde"]
kustos = ["dep:kustos"]
rand = ["dep:rand", "uuid/v4"]
redis = ["serde", "dep:redis", "dep:redis-args"]
serde = [
  "dep:serde",
  "dep:validator",
  "chrono/serde",
  "chrono-tz/serde",
]

[dev-dependencies]
pretty_assertions = "1.3"
