# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-types"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = true
description = "Shared types and traits for OpenTalk crates"

[dependencies]
actix-http = { workspace = true, optional = true }
actix-web-httpauth = { workspace = true, optional = true }
base64 = { workspace = true, optional = true }
bincode = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
chrono.workspace = true
chrono-tz.workspace = true
clap = { workspace = true, optional = true }
client-shared = { path = "../client-shared", package = "opentalk-client-shared", optional = true }
derive_more = "0.99"
diesel = { workspace = true, features = ["uuid"], optional = true }
diesel-newtype = { path = "../diesel-newtype", package = "opentalk-diesel-newtype", optional = true }
email_address.workspace = true
http = { workspace = true, optional = true }
kustos-prefix = { path = "../kustos-prefix", package = "opentalk-kustos-prefix", optional = true }
kustos-shared = { path = "../kustos-shared", optional = true }
rand = { workspace = true, optional = true }
redis = { workspace = true, optional = true }
redis-args = { path = "../redis-args", optional = true }
serde = { workspace = true, optional = true }
serde_json.workspace = true
thiserror.workspace = true
strum.workspace = true
uuid.workspace = true
validator = { workspace = true, optional = true }
url.workspace = true

[features]
default = []
actix = ["dep:actix-http", "dep:actix-web-httpauth", "dep:bytes"]
backend = ["actix", "diesel", "kustos", "rand", "redis", "serde"]
clap = ["dep:clap"]
diesel = ["serde", "dep:diesel", "dep:diesel-newtype"]
frontend = ["serde", "dep:client-shared", "dep:http"]
kustos = ["dep:kustos-prefix", "dep:kustos-shared"]
rand = ["dep:rand", "uuid/v4"]
redis = ["serde", "dep:redis", "dep:redis-args"]
serde = [
  "dep:base64",
  "dep:bincode",
  "dep:serde",
  "dep:validator",
  "chrono/serde",
  "chrono-tz/serde",
  "url/serde",
  "uuid/serde",
]

[dev-dependencies]
pretty_assertions.workspace = true
