# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-proc-macro-fields-helper"
documentation = "https://docs.rs/opentalk-proc-macro-fields-helper"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
publish = true
description = "Helper function for working with fields in proc macros, used in OpenTalk crates"

[dependencies]
quote = "1"
syn = { workspace = true }
proc-macro2 = "1"
