# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Helper function for working with fields in proc macros, used in OpenTalk crates"
documentation = "https://docs.rs/opentalk-proc-macro-fields-helper"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-proc-macro-fields-helper"
publish = true
repository.workspace = true
version.workspace = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { workspace = true }
