# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "proc-macro-fields-helper"
edition = "2021"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
quote = "1"
syn = { version = "2" }
proc-macro2 = "1"
