# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "OpenTalk API client library"
edition = "2021"
license = "EUPL-1.2"
name = "opentalk-api-client"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
http-request-derive = { workspace = true, features = ["serde"] }
opentalk-types-api-v1 = { workspace = true, features = ["frontend"] }
opentalk-types-common = { workspace = true, features = ["frontend"] }
