# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Signaling types for the OpenTalk chat module"
documentation = "https://docs.rs/opentalk-types-signaling-chat"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-types-signaling-chat"
publish = true
repository.workspace = true
version.workspace = true

[features]
backend = ["rand", "serde"]
frontend = ["serde"]
rand = ["uuid/v4"]
redis = ["dep:redis-args"]
serde = ["dep:serde", "uuid/serde"]

[dependencies]
derive_more = { workspace = true, features = [
  "as_ref",
  "display",
  "from",
  "from_str",
  "into",
] }
redis-args = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
uuid.workspace = true
