# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2021"
license = "EUPL-1.2"
name = "opentalk-protocol"
publish = false
version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
log.workspace = true
opentalk-controller-settings.workspace = true
opentalk-database.workspace = true
opentalk-etherpad-client.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types = { workspace = true, features = ["backend"] }
redis.workspace = true
redis-args.workspace = true
serde.workspace = true
snafu.workspace = true
tracing.workspace = true
