# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-protocol"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
opentalk-controller-settings.workspace = true
opentalk-database.workspace = true
opentalk-etherpad-client.workspace = true
log.workspace = true
redis-args.workspace = true
redis.workspace = true
serde.workspace = true
opentalk-signaling-core.workspace = true
tracing.workspace = true
opentalk-types = { workspace = true, features = ["backend"] }
