[package]
name = "protocol"
version = "0.1.0"
edition = "2018"

[dependencies]
controller-shared = { path = "../controller-shared-types", package = "k3k-controller-shared" }
etherpad-client = { path = "../etherpad-client", package = "etherpad-client" }
controller = { path = "../controller", package = "k3k-controller-core" }
db-storage = { path = "../db-storage", package = "k3k-db-storage" }
serde = { version = "1", features = ["derive"] }
