# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-protocol"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
controller-settings = { path = "../controller-settings", package = "opentalk-controller-settings" }
etherpad-client = { path = "../etherpad-client", package = "etherpad-client" }
controller = { path = "../controller", package = "opentalk-controller-core" }
database = { path = "../database", package = "opentalk-database" }
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
serde = { version = "1", features = ["derive"] }
redis = "0.22"
redis-args = { path = "../redis-args", package = "opentalk-redis-args" }
types = { path = "../types", package = "opentalk-types", features = ["backend"] }

[dev-dependencies]
test-util = { path = "../test-util", package = "opentalk-test-util", features = ["database"] }
pretty_assertions = "1.3"
