# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "OpenTalk Controller service facade"
documentation = "https://docs.rs/opentalk-controller-service-facade"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-controller-service-facade"
publish = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
