# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Shared types and traits for OpenTalk crates"
documentation = "https://docs.rs/opentalk-types"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-types"
publish = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
actix-http = { workspace = true, optional = true }
actix-web = { workspace = true, optional = true }
axum = { workspace = true, optional = true }
diesel = { workspace = true, features = ["uuid"], optional = true }
http = { workspace = true, optional = true }
http0 = { workspace = true, optional = true }
itertools.workspace = true
log.workspace = true
opentalk-cache = { workspace = true, optional = true }
opentalk-database = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json.workspace = true
snafu.workspace = true
utoipa = { workspace = true, features = [
  "chrono",
  "debug",
  "url",
  "uuid",
], optional = true }
validator = { workspace = true, optional = true }

[features]
actix = ["dep:actix-http", "dep:actix-web", "dep:http0", "serde"]
axum = ["dep:axum", "dep:http", "dep:http0", "serde"]
backend = [
  "actix",
  "dep:opentalk-cache",
  "dep:opentalk-database",
  "diesel",
  "serde",
  "utoipa",
]
diesel = ["dep:diesel", "serde"]
frontend = ["dep:http", "dep:http0", "serde"]
serde = ["dep:serde", "dep:validator"]
utoipa = ["dep:utoipa", "serde"]

[dev-dependencies]
pretty_assertions.workspace = true
