# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "kustos"
version = "0.1.0"
edition = "2021"
license = "EUPL-1.2"
authors.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = { path = "../database", package = "opentalk-database" }

## Database migration
barrel = { version = "0.7", features = ["pg"] }

### Error handling
thiserror = "1.0"
anyhow = "1.0.69"
http = "0.2.9"

### Database ORM
diesel = { version = "2", features = [
    "postgres",
    "uuid",
    "serde_json",
    "chrono",
] }
diesel-async = "0.2"
uuid = { version = "1.3.0", features = ["serde", "v4"] }

### Logging utilities
log = { version = "0.4", features = ["serde"] }
tracing = { version = "0.1" }
tracing-futures = "0.2"

### QoL
itertools = "0.10"
futures = "0.3"
async-trait = "0.1"

tokio = { version = "1", features = ["macros"] }
parking_lot = "0.12"

### TODO(r.floren) add this as a default feature
actix-web = { version = "4" }

### Opentelementry metrics
opentelemetry = { version = "0.18", default-features = false, features = [
    "metrics",
] }

[dependencies.casbin]
git = "https://github.com/kbalt/casbin-rs.git"
rev = "a5cd79704726b423030942769779ea7d4e8129ee"
default-features = false
features = ["runtime-tokio", "incremental"]

[dev-dependencies]
serial_test = "1"
anyhow = "1.0"
# TODO(r.floren) remove this in the future. Currently used to migrate in tests. Find something lighter.
db-storage = { path = "../db-storage", package = "opentalk-db-storage" }
url = "2"
tokio = { version = "1", features = ["rt", "macros"] }
pretty_assertions = "1.3"
